# Generated by Django 3.2.8 on 2021-10-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('format', models.CharField(choices=[('Excel', 'Excel'), ('CSV', 'CSV')], default='Excel', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('schedule', models.CharField(choices=[('NoRepeat', 'NoRepear'), ('Specific', 'Specific'), ('Daily', 'Daily'), ('Weekly', 'Weekly')], max_length=130)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('day', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
